# Generated by Django 4.0.4 on 2022-05-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
